apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rules.kwaf.io
spec:
  group: kwaf.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
              pattern:
                type: string
              action:
                type: string
  scope: Namespaced
  names:
    plural: rules
    singular: rule
    kind: Rule
    shortNames:
    - kwafrule
